### ISSUE TITLE
error

### ISSUE THREAD

**Issue by intersectin** [Gowixx/okuru-nuker#13]
i get

```

Traceback (most recent call last):
  File "C:\Users\Velorism\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Velorism\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Velorism\Downloads\okuru-nuker-main (2)\okuru-nuker-main\main.py", line 15, in <module>
    config = json.load(open('config.json'))
  File "C:\Users\Velorism\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Velorism\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Velorism\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Velorism\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 18 column 1 (char 513)

C:\Users\Velorism\Downloads\okuru-nuker-main (2)\okuru-nuker-main

**Comment by AstroidDev** [comment]
Your json is messed up on like 18, you forgot to add ","

**Comment by intersectin** [comment]
thanks!
